name: PyPI

on:
  release:
    types: [created]

jobs:
  test:
    uses: ./.github/workflows/pytest.yaml
  static-type-check:
    uses: ./.github/workflows/static-type-check.yaml
  code-style-check:
    uses: ./.github/workflows/code-style-check.yaml
  deploy:
    needs: [test, static-type-check, code-style-check]
    runs-on: ubuntu-latest
    env:
      PRIVATE_REPO_USER: "hmasdev"
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Init .pypirc
        run: |
          echo -e '[pypi]' >> ~/.pypirc
          echo -e "username: ${{ secrets.PYPI_USERNAME }}" >> ~/.pypirc
          echo -e "password: ${{ secrets.PYPI_PASSWORD }}" >> ~/.pypirc
      - name: Upload
        run: |
          pipenv run python setup.py sdist bdist_wheel
          pipenv run twine upload --repository pypi dist/*
      - name: Delete .pypirc
        run: |
          rm ~/.pypirc
      - name: Delete virtualenv
        run: |
          pipenv --rm
