name: Pytest

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Lint
        run: |
          pipenv sync --dev
          pipenv run flake8 . --show-source
      - name: Test
        run: |
          pipenv sync --dev
          sh ./download_html_for_test.sh
          pipenv run pytest
          pipenv --rm
