name: Validate Version

on:
  workflow_dispatch:
    inputs:
      git-ref:
        required: false
        type: string
        default: "main"
  workflow_call:
    inputs:
      git-ref:
        required: false
        type: string
        default: "main"

jobs:
  validate_version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.git-ref }}
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          python -m pip install uv
          uv sync
      - name: Check Version
        run: |
          # Check if the tag is the same as pyjpboatrace.__version__
          export tag=$(echo "$INPUTS_GIT_REF" | cut -d / -f 3)
          echo "extracted tag from git-ref: $tag"
          uv run python -c "import os; import pyjpboatrace; assert pyjpboatrace.__version__ == os.getenv('tag'), (pyjpboatrace.__version__, os.getenv('tag'))"
        env:
          INPUTS_GIT_REF: ${{ inputs.git-ref }}
